spring:
  resources:
    cache:
      cachecontrol:
        no-cache: true
        no-store: true
        max-age: 0d

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none